---
- hosts: all
  become: true
  tasks:
    - name: Install httpd service
      yum:
        name: httpd
        state: latest
    - name: Restart httpd service
      service:
        name: httpd
        state: restarted
#TESTing Git Chnages